name: snap-processing # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's Processing but in a Snap! # 79 char long summary
description: |
  I've tried to install processing as a snap instead of a docker container because it's a good opportunity to learn.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cli:
    command: processing-java
  gui:
    command: processing

parts:
  processing:
    plugin: dump
    source: http://download.processing.org/processing-3.4-linux64.tgz
    stage-packages:
      - openjdk-8-jdk
