name: processing # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's Processing but in a Snap! # 79 char long summary
description: |
  I've tried to install processing as a snap instead of a docker container because it's a good opportunity to learn.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cli:
    command: processing-java
  gui:
    command: processing
    plugs:
      - x11
      - wayland # let it run on wayland, because it's gtk3 so it should be fine
      - desktop # needed for a lot of gtk3 and glib interaction with the host system
      - desktop-legacy # needed for accessibility tools IIRC
      - network-bind

parts:
  processing:
    plugin: dump
    source: http://download.processing.org/processing-3.4-linux64.tgz
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - openjdk-8-jdk
